### ISSUE TITLE
Breaks when `package-lock.json` is gitignored

### ISSUE THREAD

**Issue by chasingSublimity** [activeprospect/cut-release#6]
> The command `npm version 0.1.1` failed:
Command failed: npm version 0.1.1
npm ERR! code 1
npm ERR! Command failed: git add /Users/blakesager/Documents/leadconduit/Integrations/leadconduit-integration-ebureau/package-lock.json
npm ERR! The following paths are ignored by one of your .gitignore files:
npm ERR! package-lock.json
npm ERR! Use -f if you really want to add them.
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blakesager/.npm/_logs/2017-11-21T17_56_06_689Z-debug.log

**Comment by chasingSublimity** [comment]
Re: package-lock and cut-release, it looks like the options are:

1) Keep the lock file in .gitignore and add the `-f` flag to `npm version`
2) Remove the lock file from .gitiginore and commit it
3) Keep the lock file in .gitignore and avoid generating the damn thing  in the first place

Thoughts?

**Comment by alexkwolfe** [comment]
Per [this comment](https://github.com/npm/npm/issues/17168#issuecomment-330411787), we could also make a change to the .npmrc file in the leadconduit-api repo.

That setting prevents the package-lock.json file from getting created. The nice thing is that once package-lock.json is actually useful, we can remove this setting in the code and it'll start working. No need to have each individual dev remove it from their local npm config.

**Comment by chasingSublimity** [comment]
Heard. We'd have to add the `.npmrc` file to every repo that is `cut-released`, correct?

**Comment by alexkwolfe** [comment]
Yeah. It should be there already for all private packages.

**Comment by chasingSublimity** [comment]
Ok cool. I think I've encountered (read: written) a few w/o `rc` files, but that's a quick fix. I'll close this if you're good with it.

**Comment by alexkwolfe** [comment]
👍
